# Generated by Django 3.0.2 on 2024-12-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckdApp', '0003_auto_20241205_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckdmodel',
            name='airconditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='basement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='furnishingstatus_semi_furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='furnishingstatus_unfurnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='guestroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='hotwaterheating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='mainroad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='prefarea',
            field=models.BooleanField(default=False),
        ),
    ]
