# Generated by Django 3.0.2 on 2024-12-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckdApp', '0004_auto_20241205_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='airconditioning',
            new_name='airconditioning_yes',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='basement',
            new_name='basement_yes',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='guestroom',
            new_name='guestroom_yes',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='hotwaterheating',
            new_name='hotwaterheating_yes',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='mainroad',
            new_name='mainroad_yes',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='prefarea',
            new_name='prefarea_yes',
        ),
    ]
